### ISSUE TITLE
0 rendered as empty

### ISSUE THREAD

**Issue by JorisVB** [maikelbos0/VDT#1]
The populate functions sets the cell's content like this:
cell.text(dataRow[column.data] || "").attr('title', dataRow[column.data] || "");

This works as intended for undefined or null javascript being javascript, the result for 0 || "" is the empty string, swallowing the 0.

Same thing happens when rendering totals in the populate method.

**Comment by maikelbos0** [comment]
Thanks, the bug has been fixed in the just released version 1.2.3.
